database:
  dsn: "postgresql://alisakr:2tcWfZK8kmhQnHUytUIFCA@free-tier4.aws-us-west-2.cockroachlabs.cloud:26257/tribaltransacion?sslmode=verify-full&options=--cluster%3Dslimy-hulk-3586"
kafka:
  broker: "localhost:9092"
  topic: "topic_transaction"
  maxBytes: 30
